### ISSUE TITLE
Remove Source Maps

### ISSUE THREAD

**Issue by ArquintL** [cotag/ts-md5#1]
The module on NPM includes a reference to md5.js.map.
I use webpack in my project to combine my own code with all modules in a single file. When I load this bundle afterwards in a browser, I get an error that md5.js.map couldn't be loaded (because I don't copy it to the output directory).
I just tried to fork the repo and solve it myself, but unfortunately all dependencies are set to `latest` and due to the change to TS 2.0 (at least I think this is the reason) the project currently can't be compiled successfully.

@stakach: What versions of your dependencies have you used the last time you successfully compiled the sources?

**Comment by stakach** [comment]
You should be able to build the project now
