### ISSUE TITLE
SyntaxError: expected expression, got '<' 

### ISSUE THREAD

**Issue by HADDADENICAR** [cotag/ts-md5#12]
while i try to run md5 for a file i get this erreur:

    SyntaxError: expected expression, got '<' 

this is my code:

     let hasher = new ParallelHasher('ECHRI-ADMIN-WEB-APP/node_modules/ts-md5/dist             /md5_worker.js');
     hasher.hash(file);

how to solve it ?

**Comment by stakach** [comment]
should be resolved
