### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by Larsrdev** [cotag/ts-md5#13]
Hey, we wan't to use your project, but there is a licence missing in your project :) 
Thanks a lot.

**Comment by stakach** [comment]
Just no license file. It's MIT
https://github.com/cotag/ts-md5/blob/master/package.json#L23

**Comment by stakach** [comment]
Also in the source
https://github.com/cotag/ts-md5/blob/master/src/md5.ts#L13

**Comment by Larsrdev** [comment]
thanks man, I haven't looked in the source :)
