### ISSUE TITLE
Cannot find name 'WorkerOptions'.

### ISSUE THREAD

**Issue by duanhjlt** [cotag/ts-md5#17]
I have update ts-md5 to 1.2.5. and get the error

Cannot find name 'WorkerOptions'.

constructor(workerUri: string, workerOptions?: WorkerOptions);

**Comment by Devsnapper** [comment]
try to remove  workerOptions?: WorkerOptions then it will work but still it is a temp solution only..

**Comment by duanhjlt** [comment]
1.2.5 has published. So I met the error.
And now the use 1.2.4.

Could you fix it?

**Comment by duanhjlt** [comment]
I reduced to 1.2.4.....

**Comment by Devsnapper** [comment]
@duanhjlt  if i reduced to 1.2.4 also i am facing this issue

**Comment by stakach** [comment]
fixed by #20
