### ISSUE TITLE
md5_worker: "require is not defined"

### ISSUE THREAD

**Issue by elgiano** [cotag/ts-md5#33]
I read it happened and was fixed before... well, here we are again:
https://github.com/cotag/ts-md5/blob/e36f078b95dc5a87a17f8970eaa9d1c45177dbad/dist/md5_worker.js#L400

**Comment by spsDrop** [comment]
Someone needs to merge that fix. This is just broken. I just hand copied the file and changed 

`var md5_1 = require("./md5");`

to

`var md5_1 = { Md5 }`
