### ISSUE TITLE
 Error: 'Md5' is not exported by node_modules\ts-md5\dist\md5.js

### ISSUE THREAD

**Issue by aijingsun6** [cotag/ts-md5#4]
when i use rollup funciton in angular project,then i got an error, logs below:

...
Error: 'Md5' is not exported by node_modules\ts-md5\dist\md5.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
...
then
i modofy file dist\md5.js
var Md5 ... to export var Md5
it works
yours

**Comment by stakach** [comment]
I released a new version of the project. Can you check if this resolves the issue?
v1.2.2

**Comment by WeekendMan** [comment]
Have the same issue:
```
import { Md5 } from 'ts-md5/dist/md5';

export class Zzz {
  constructor() {
    Md5.hashString('zzzz');// Uncaught ReferenceError: Md5 is not defined
  }
}
```
Angular2

**Comment by johnbendi** [comment]
@stakach I'm getting this error message
```
Error: Cannot find module 'ts-md5'
```
when using webpack dll plugin. I think this issue has to do with not having a `main:` entry in package.json?

**Comment by johnbendi** [comment]
Yes! I just confirmed that adding a `"main": "dist/md5.js" ` solves this error.

**Comment by stakach** [comment]
Thanks, I've published a new version

**Comment by dyh333** [comment]
@stakach , i have update to v1.2.3, but when i use rollup funciton in angular project, still got an error
![image](https://user-images.githubusercontent.com/1221313/35508730-6bd37fee-052c-11e8-8596-4ddc611d988f.png)

**Comment by dyh333** [comment]
@aijingsun6  do you solved it?
