### ISSUE TITLE
hashString vs hashAsciiString

### ISSUE THREAD

**Issue by sebthom** [cotag/ts-md5#42]
Hi I am trying to use your library but I am unsure which method (hashString or hashAsciiString) to use.

What is the difference between:
```typescript
Md5.hashString("foobar")
Md5.hashAsciiString("foobar")
```
and when to use which?

Thanks in advance!

**Comment by stakach** [comment]
ascii is faster, no other difference

**Comment by sebthom** [comment]
ok, thanks!
