### ISSUE TITLE
Calculate MD5 from file path

### ISSUE THREAD

**Issue by Anil8753** [cotag/ts-md5#5]
We can calculate md5 from blob, 
```
import {ParallelHasher} from 'ts-md5/dist/parallel_hasher';
 
let hasher = new ParallelHasher('/path/to/ts-md5/dist/md5_worker.js');
hasher.hash(fileBlob).then(function(result) {
   console.log('md5 of fileBlob is', result);
});
```

If we can calculate MD5 from file path as well that will good.

**Comment by stakach** [comment]
Do you want to hash the file path string?
Or do you want to hash the file?

**Comment by Anil8753** [comment]
Hash of a file from the file path.

**Comment by stakach** [comment]
It's not really possible - you can grab the blobs from a file input box or from a drag and drop event.

**Comment by Anil8753** [comment]
Thank you. You may take it as a feature request and close this issue. 👍
