### ISSUE TITLE
Fix documentation: import changed in version 1.3.0

### ISSUE THREAD

**Issue by bhalperin** [cotag/ts-md5#53]
`import { Md5 } from 'ts-md5/dist/esm/md5';`
`import { Md5 } from 'ts-md5/dist/cjs/md5';`
instead of
`import { Md5 } from 'ts-md5/dist/md5';`

**Comment by MrYuion** [comment]
Unless you want a specific file you should just import from the root instead of the specific file.
e.g. `import { Md5 } from 'ts-md5';`
I've re-added the file in that location for backward compatibility.
