### ISSUE TITLE
I need to Hash a variable not a string, how can I do that ?

### ISSUE THREAD

**Issue by tomavic** [cotag/ts-md5#6]

**Comment by ForrestGumpForever** [comment]
Sorry I can't understand what "Hash a variable" is !

**Comment by stakach** [comment]
You'd need to serialise it into a string or "binary string" or byte array to perform the hash

**Comment by tomavic** [comment]
Here is what I am doing:

I am creating md5 hash for token which is generated by sequence :
` let token: number = (2017*5) + (10*6) + (10*6) `

and when I tried  ` let hashedToken:any = Md5.hashStr(token); ` 

it generates an error , then I navigated to md5.d.ts and I edited next line from 

`   static hashStr(str: string, raw?: boolean): string | Int32Array; `  

to 

`     static hashStr(str: any, raw?: boolean): string | Int32Array; `

**Comment by tomavic** [comment]
So What I was asking for a way without editing your source code !

**Comment by Jrubzjeknf** [comment]
Yes, you can turn the number into a string by calling toString() on your token variable.

    token.toString()
